name: Algorithms validation

on:
  push:
    branches:
      - main
      - develop

jobs:
  run-tests:
    name: Run validation tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Execute tests
        run: python -m unittest discover tests
