name: Algorithms validation

on: push

jobs:
  run-tests:
    name: Run validation tests
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Display python version for sanity check
        run: |
          ls
          python -c "import sys; print(sys.version)"
      - name: Execute tests
        run: python -m unittest discover

#  job_2:
#    name: <name of the second job>
#    runs-on: <type of machine to run the job on>
#    steps:
#      - name: <step 1>
#        run: |
#          <commands>
#      - name: <step 2>
#        run: |
#          <commands>